server:
  port: 9080

world:
  config:
    customer-search:
      found: true
      delay: 1000ms
    customer-create:
      delay: 100ms
    customer-update:
      delay: 100ms
    party-data-search:
      found: true
      delay: 100ms
    party-address-search:
      found: true
      delay: 100ms