server:
  port: 9080

world:
  config:
    customer-search:
      found: false
      delay: 100ms
    customer-create:
      delay: 100ms
    party-data-search:
      found: true
      delay: 100ms
    party-address-search:
      found: true
      delay: 100ms